---
defaults:
    - executor: local
    - autotuner: random
    - benchmarks: cbench
search_time_seconds: 3600
# The base directory for logs and other runtime artifacts.
outputs: ${env:HOME}/logs/compiler_gym/llvm_autotuning
# The top subdirectory to arrange files in. Use this to group related runs by
# some logical naming.
experiment: unnamed_experiment
# The number of replicas of each autotuning job to run.
num_replicas: 10
# Use hydra to manage the output directory layout. Multi-run and single runs
# share the same directory layout (there just won't be a multirun.yaml file for
# the individual runs).
hydra:
    run:
        dir: ${outputs}/${experiment}/${now:%Y-%m-%d}/${now:%H-%M-%S}/${experiment}-C0
    sweep:
        dir: ${outputs}/${experiment}/${now:%Y-%m-%d}/${now:%H-%M-%S}
        subdir: ${experiment}-C${hydra.job.num}
    output_subdir: hydra
